substitutions:
  GCP_REGION: 'us-west2'
  GCP_CONTAINER_REGISTRY_REPOSITORY_NAME: 'quickstart-docker-repo'
  DOCKER_IMAGE_NAME: 'quickstart-image'
  GCP_CLOUD_RUN_SERVICE_NAME: 'my-service'

steps:
  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=GCP_REGION=$GCP_REGION'
      - '--build-arg=PROJECT_ID=$PROJECT_ID'
      - '--build-arg=GCP_CONTAINER_REGISTRY_REPOSITORY_NAME=$GCP_CONTAINER_REGISTRY_REPOSITORY_NAME'
      - '--build-arg=DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME'
      - '-t'
      - '$GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCP_CONTAINER_REGISTRY_REPOSITORY_NAME/$DOCKER_IMAGE_NAME:$SHORT_SHA'
      - '.'

  # Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCP_CONTAINER_REGISTRY_REPOSITORY_NAME/$DOCKER_IMAGE_NAME:$SHORT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - '$GCP_CLOUD_RUN_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$GCP_CONTAINER_REGISTRY_REPOSITORY_NAME/$DOCKER_IMAGE_NAME:$SHORT_SHA'
      - '--region'
      - '$GCP_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/$GCP_CONTAINER_REGISTRY_REPOSITORY_NAME/$DOCKER_IMAGE_NAME:$SHORT_SHA'
