substitutions:
  _GCP_REGION: 'us-west2'
  _PROJECT_ID: 'tfc-cloud-build'
  _GCP_CONTAINER_REGISTRY_REPOSITORY_NAME: 'quickstart-docker-repo'
  _DOCKER_IMAGE_NAME: 'quickstart-image'
  _GCP_CLOUD_RUN_SERVICE_NAME: 'my-service'

steps:
  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=GCP_REGION=$_GCP_REGION'
      - '--build-arg=PROJECT_ID=$_PROJECT_ID'
      - '--build-arg=GCP_CONTAINER_REGISTRY_REPOSITORY_NAME=$_GCP_CONTAINER_REGISTRY_REPOSITORY_NAME'
      - '--build-arg=DOCKER_IMAGE_NAME=$_DOCKER_IMAGE_NAME'
      - '-t'
      - '$_GCP_REGION-docker.pkg.dev/$_PROJECT_ID/$_GCP_CONTAINER_REGISTRY_REPOSITORY_NAME/$_DOCKER_IMAGE_NAME:$SHORT_SHA'
      - '.'

  # Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_GCP_REGION-docker.pkg.dev/$_PROJECT_ID/$_GCP_CONTAINER_REGISTRY_REPOSITORY_NAME/$_DOCKER_IMAGE_NAME:$SHORT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - '$_GCP_CLOUD_RUN_SERVICE_NAME'
      - '--image'
      - '$_GCP_REGION-docker.pkg.dev/$_PROJECT_ID/$_GCP_CONTAINER_REGISTRY_REPOSITORY_NAME/$_DOCKER_IMAGE_NAME:$SHORT_SHA'
      - '--region'
      - '$_GCP_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - '$_GCP_REGION-docker.pkg.dev/$_PROJECT_ID/$_GCP_CONTAINER_REGISTRY_REPOSITORY_NAME/$_DOCKER_IMAGE_NAME:$SHORT_SHA'
